jobs:
  - name: pipeline-init
    type: runSh
    on_start:
      - script: echo "starting pipeline-init job"
    steps:
      - IN: github-repo
      - TASK:
        - script: echo "running a task"
    on_success:
      - script: echo "finished - success"
